name: PHPUnit Tests

on:
  pull_request:
    branches:
      - master  # You can specify the branches where this action should run
      - main  # You can specify the branches where this action should run

jobs:
  phpunit-test:
    runs-on: ubuntu-latest
    needs: semantic-release

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'  # Specify the PHP version you need
        extensions: mbstring, intl, dom, json, pdo, pdo_mysql, pdo_pgsql, pdo_sqlite, sqlite3, xml

    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Install Xdebug
      run: |
        pecl install xdebug
        echo "zend_extension=$(php -r 'echo ini_get("extension_dir");')/xdebug.so" >> $(php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||")
        echo "xdebug.mode=coverage" >> $(php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||")
        echo "xdebug.start_with_request=yes" >> $(php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||")
        php -v
        php -m

    - name: PHPUnit Tests
        run: composer run-script test

    with:
        configuration: "phpunit.xml"
        memory_limit: "256M"
    # ... then your own project steps ...