name: Pull Request Check

on:
  pull_request: {}

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: php-actions/composer@v6 # or alternative dependency management

    - name: PHPUnit Tests
        uses: php-actions/phpunit@master
        env:
          TEST_NAME: unit
        with:
          version: 9.6
          php_version: 8.3
          bootstrap: vendor/autoload.php
          configuration: phpunit.xml
          args: --coverage-text

    with:
        configuration: "phpunit.xml"
        memory_limit: "256M"
    # ... then your own project steps ...